### ISSUE TITLE
Can you add an animated GIF or an MP4 file (and screenshots) to your readme?

### ISSUE THREAD

**Issue by PySimpleGUI** [dirsense/Tableau_Auto_Document#1]
Your tool is incredible and extremely visual.  I'm sure visitors to his repo would love to see information in the readme so that it's immediately visible without going to YouTube.

I ![image](https://github.com/dirsense/Tableau_Auto_Document/assets/46163555/4cf6eeec-f59a-49e5-8887-fb41ce555c16) that you've made a toolchain / pipeline that includes PySimpleGUI.

Since you know how to use PySimpleGUI, there may be some situations where it's easy to make a dashboard or graph using PySimpleGUI.

Here are a few I've made.  There are quite a few in the PySimpleGUI Demo Programs.  You can see [some screenshots here](https://www.pysimplegui.org/en/latest/Demos/).

![CPU](https://raw.githubusercontent.com/PySimpleGUI/PySimpleGUI/master/images/for_readme/CPU%20Cores%20Dashboard%202.gif)
![SNAG-1895](https://github.com/PySimpleGUI/PySimpleGUI/assets/46163555/bfd8dfec-e2c4-4ced-9e45-8622e8e112da)
![image](https://github.com/dirsense/Tableau_Auto_Document/assets/46163555/9a52e0e2-6a42-4a00-94b0-6b2bbeca8451)

**Comment by dirsense** [comment]
Thanks for the advice! You are indeed right. My readme lacked visual clarity, unlike the tool.
I just updated the readme with more images and videos and better explanations. I think it looks much better.
I like PySimpleGUI very much. I am very honored and happy that you sent me a comment from its official account.

Awesome. It would be interesting to create various graphs using PySimpleGUI.
I will appreciate the information you have given me. Thank you.
